services:
  - type: web
    name: discord-music-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: discord-bot-secrets
    scaling:
      minInstances: 1
      maxInstances: 1